// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axjiqmafjhidlsmnziph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4amlxbWFmamhpZGxzbW56aXBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NzQzNzMsImV4cCI6MjA2MDM1MDM3M30.tmh3BSe42-3XjHBv7vYrDMNvaWuflaJtcBxnbTh8O2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);